### ISSUE TITLE
Error creating organization: AccessDeniedException: You don't have permissions to access this resource.

### ISSUE THREAD

**Issue by LennyCastaneda** [aws-samples/amazon-guardduty-for-aws-organizations-with-terraform#1] opened 2022-06-08 23:42 UTC
Hello, thanks for creating these modules, it is helping bootstrap a similar design I'm creating. I am encountering a permissions error that is a bit tricky to debug. When using the [import-org module](https://github.com/aws-samples/amazon-guardduty-for-aws-organizations-with-terraform/tree/main/import-org), I'm seeing this permissions error even though I'm applying the [management account policy](https://github.com/aws-samples/amazon-guardduty-for-aws-organizations-with-terraform/blob/main/management-account-role-policy.json) to my GaurdDuty_Admin role that exists in Management account and in Security accounts.

My only difference is I am using Security Account to store S3 remote state and DynamoDB locking table and only assuming role into Management account to import organization and then enable the [AWS service access principals](https://github.com/aws-samples/amazon-guardduty-for-aws-organizations-with-terraform/blob/main/import-org/org.tf#L22-L26).

`Error: Error creating organization: AccessDeniedException: You don't have permissions to access this resource.
│ 
│   with aws_organizations_organization.metallicus,
│   on main.tf line 5, in resource "aws_organizations_organization" "metallicus":
│    5: resource "aws_organizations_organization" "metallicus" {`

Even when setting the organization permissions to allow all as a test, still get the same error.

`          "Sid": "OrgPerms",
            "Effect": "Allow",
            "Action": [
                "organizations*"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:PrincipalOrgId": ["<Enter your Org ID here>"]
                }
            }
        }`
        
        
Is there anything else in the policy that could be missing in order to import a currently existing AWS Organization and allowed to enable those [access principals] using this module?(https://github.com/aws-samples/amazon-guardduty-for-aws-organizations-with-terraform/blob/main/import-org/org.tf#L22-L26)  

Looking forward to your response.

**Comment by aarthkan** [comment] 2022-06-09 14:10
Hi, 
Thanks for sharing your feedback !
Reiterating my understanding of your issue, you are replicating the same model but with the TFM state stored in the security account (also the delegated admin account). I did a quick check with my code and performed the following actions:
1. Change the state bucket and DynDB table information to point to resources in the Security account; create the required access policies for these resources.
2. Create a role in the Management account with Organizations and GuardDuty permissions (covered in Sids OrgPerms, GdInOrg, IAMRoleCreate under management-account-role-policy.json). No additional permissions are needed.
3. Add 'assume_role' to the provider in import_org/ module and set it to the role ARN created in (2) above.
4. Run terraform init/import/apply for import_org with session created based on Security account credentials.
With these steps, I was able to successfully import the organization module with remote state saved in the Security account. Do try this out and let me know how it works !
I don't think there is a problem with the permissions and the issue is more due to the change in structure which requires some adjustments.

**Comment by LennyCastaneda** [comment] 2022-06-09 22:17
Thanks for the response @aarthkan... quick question, does the IAMRoleCreate under management-account-role-policy.json still use the management-account-id or security-account-id?

**Comment by LennyCastaneda** [comment] 2022-06-09 22:21
Also to give you additional context, I am using AWS SSO to authenticate into AWS and I assume an AWS Permission Set role that I created in the Security Account. This could be the reason I encounter access deny errors why since maybe your solution assumes an engineer logs in via User or Human Role credentials?

**Comment by LennyCastaneda** [comment] 2022-06-10 22:53
Got it working. Thank you so much for your help @aarthkan

**Comment by aarthkan** [comment] 2022-06-11 02:56
Happy to help !
I will be closing this issue now.

**Closed as completed by aarthkan** 2022-06-11 02:56 UTC
